"""add utterances table

Revision ID: 776a5d3e1eb0
Revises: cc5bffd726f8
Create Date: 2026-07-31 08:27:54.614326
"""
from alembic import op
import sqlalchemy as sa


revision = '776a5d3e1eb0'
down_revision = 'cc5bffd726f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utterances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utterances_video_id'), 'utterances', ['video_id'], unique=False)
    # The BM25 functional GIN indexes from the initial migration are kept —
    # autogenerate wrongly proposed dropping them (it can't see raw-SQL indexes).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utterances_video_id'), table_name='utterances')
    op.drop_table('utterances')
    # ### end Alembic commands ###
