"""initial schema

Revision ID: cc5bffd726f8
Revises: 
Create Date: 2026-07-31 03:23:07.059421
"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

revision = 'cc5bffd726f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), nullable=True),
    sa.Column('structured_ref', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policies_category'), 'policies', ['category'], unique=False)
    op.create_table('policy_change_requests',
    sa.Column('req_id', sa.String(), nullable=False),
    sa.Column('proposed_change', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('affected_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('similar_policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('req_id')
    )
    op.create_index(op.f('ix_policy_change_requests_status'), 'policy_change_requests', ['status'], unique=False)
    op.create_table('policy_sets',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('source_blob', sa.String(), nullable=True),
    sa.Column('global_overview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('text_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('segments',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('clip_blob', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('base_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), nullable=True),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_segments_video_id'), 'segments', ['video_id'], unique=False)
    op.create_table('labels',
    sa.Column('label_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('cited_policy_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('used_segment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_labels_category'), 'labels', ['category'], unique=False)
    op.create_index(op.f('ix_labels_segment_id'), 'labels', ['segment_id'], unique=False)
    # ### end Alembic commands ###

    # BM25/full-text (lexical) — tsvector GIN indexes. 'simple' config is
    # language-agnostic (dataset mixes KO/EN). Dense vectors are searched
    # brute-force in the PoC (3072-dim exceeds pgvector's 2000-dim ANN limit).
    op.execute("CREATE INDEX ix_policies_text_fts ON policies "
               "USING gin (to_tsvector('simple', text))")
    op.execute("CREATE INDEX ix_segments_transcript_fts ON segments "
               "USING gin (to_tsvector('simple', coalesce(transcript, '')))")
    op.execute("CREATE INDEX ix_segments_summary_fts ON segments "
               "USING gin (to_tsvector('simple', coalesce(summary, '')))")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_segments_summary_fts")
    op.execute("DROP INDEX IF EXISTS ix_segments_transcript_fts")
    op.execute("DROP INDEX IF EXISTS ix_policies_text_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_segment_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_category'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_segments_video_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_table('videos')
    op.drop_table('policy_sets')
    op.drop_index(op.f('ix_policy_change_requests_status'), table_name='policy_change_requests')
    op.drop_table('policy_change_requests')
    op.drop_index(op.f('ix_policies_category'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
